image: docker:latest
services:
  - docker:dind
stage: 
  -build
  -package
  -deploy
maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.war
docker-build:
  stage: package
  bofre_script:
    -dokcer login -y $CI_REGISTRY -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    -docker build --pull -t "$CI_REGISTRY_IMAGE" .
    -docker push "$CI_REGISTRY_IMAGE"

K8s-deploy:
  stage: deploy
  script:
    -docker run -d -p 8080:8080 --name my-app "$CI_REGISTRY_IMAGE"